[workspace]
members = [
    "programs/*"
]
resolver = "2"

[profile.release]
overflow-checks = true
lto = false
codegen-units = 256
opt-level = "z"

[profile.release.build-override]
opt-level = "z"
incremental = false
codegen-units = 256
